#!/bin/bash

sudo apt install libopencv-dev -y
sudo apt-get install build-essential -y
sudo apt install npm -y
sudo apt install python3-pip && sudo pip install pipenv
sudo apt  install ffmpeg
sudo apt install rename



cd src
cd disk
make
mv disk ../../
cd ..
cd page
make
mv page ../../
cd ..
cd ..

mkdir PROCESSING_ZONE
