#!/bin/bash

sudo apt install libopencv-dev -y
sudo apt-get install build-essential -y
sudo apt install npm -y
sudo apt install python3-pip && sudo pip install pipenv -y
sudo apt  install ffmpeg -y
sudo apt install rename -y
pip install -U scikit-learn 
pip install matplotlib 

pip install tmdbsimple 




cd src
cd disk
make
mv disk ../../
cd ..
cd page
make
mv page ../../
cd ..
cd ..

mkdir PROCESSING_ZONE
