#!/bin/bash

cd PROCESSING_ZONE
rename  's/[()]//g' *
rename  's/[ :!]/_/g' *
for file in *
do
mkdir "${file%.*}"
mkdir "${file%.*}"/images
len=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $file)

echo "${file%.*}"
echo "Extracting frames"

r=$(echo "$len / 2005" | bc -l)
for i in {0..2003}  
do  
stamp=$(echo "$i * $r" | bc -l)

ffmpeg -y -nostdin -hide_banner -loglevel panic -accurate_seek -ss $stamp  -i  $file -vf "cropdetect=24:16:0" -q:v 1  -frames:v 1 "${file%.*}"/images/$i.jpg &  
done &


number_of_processed_frames=$(ls "${file%.*}"/images | wc -l)
while ((number_of_processed_frames<2000))
do 
((number_of_processed_frames=$(ls "${file%.*}"/images | wc -l)))
done


rm $file


cp ../disk  "${file%.*}"/
cd ""${file%.*}""/
num=$(ls -l images | egrep -c '^-')-2000
echo "${num}"
./disk 2000
cd ..
done 

for file in *
do
cd "${file}"/
mv "save.png" "${file}.png"
mv *.png ..
cd ..
done
